### ISSUE TITLE
fix-csv doesn't work without --pare

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/MacFound#16]
Somehow the implementation of `--pare` broke the code when `--pare` is **not** passed :-).  This is with `fix-csv` of commit 02e262229:

    $ ./fix-csv usual-csv-file sanitized-usual-csv-file
    Traceback (most recent call last):
      File "./fix-csv", line 251, in <module>
        main()
      File "./fix-csv", line 248, in main
        fix_csv(args[0], args[1], pare, show_table_problem)    
      File "./fix-csv", line 163, in fix_csv
        soup = fix_anchors(soup)
      File "./fix-csv", line 107, in fix_anchors
        BeautifulSoup(u"[{1} {0}]".format(a.text, a['href']), 'html.parser'))
      File "/usr/lib/python2.7/dist-packages/bs4/element.py", line 997, in __getitem__
        return self.attrs[key]
    KeyError: 'href'
    $

**Comment by kfogel** [comment]
Okay, progress: with commit 905ef0d09278e of `fix-csv` (the commit in which the divide-by-zero buglet with `--pare` was fixed), the error when running without `--pare` goes away.

Time for a little `git bisect` action :-).

**Comment by kfogel** [comment]
Ok, the bug was introduced in commit ccb5b79fac.  Diving in now.

**Comment by kfogel** [comment]
It seems obvious that the issue here is not about the absence of `--pare` _per se_, it's just that there are some entries in the CSV that `fix_anchors()` throws an error on, and those entries happened to be masked out when we pass `--pare=100`.  Aha: yes, if you do `--pare=73`, you'll get the same error.

Closing this issue and opening new issue #17 for what we now know is a `fix_anchors()` bug.
