### ISSUE TITLE
fix_anchors() throws an exception on some entries

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/MacFound#17]
Try running with `--pare=73`, and get this:

    Traceback (most recent call last):
      File "./fix-csv", line 256, in <module>
        main()
      File "./fix-csv", line 253, in main
        fix_csv(args[0], args[1], pare, show_table_problem)    
      File "./fix-csv", line 169, in fix_csv
        soup = fix_anchors(soup)
      File "./fix-csv", line 107, in fix_anchors
        BeautifulSoup(u"[{1} {0}]".format(a.text, a['href']), 'html.parser'))
      File "/usr/lib/python2.7/dist-packages/bs4/element.py", line 997, in __getitem__
        return self.attrs[key]
    KeyError: 'href'

**Comment by kfogel** [comment]
Fixed in commit e301c83.  In case anyone's curious, here's the entire set of anchors in the input that do not have "href" attributes:

    <a name="m_6674743261270812762__GoBack"></a>
    <a><span style="color: #000000;">benefits</span></a>
    <a name="_Toc317431739"></a>
    <a name="_Toc443314414"></a>
    <a name="_Toc317431740"></a>
    <a name="_Toc443314415"></a>
    <a name="_Toc317431735"></a>
    <a name="_Toc443314409"></a>
    <a name="_Toc317431736"></a>
    <a name="_Toc443314410"></a>
    <a name="_Toc331269015"></a>
    <a name="_Toc331268840"></a>
    <a name="_Toc326833624"></a>
    <a name="_Toc311125106"></a>
    <a name="intr2015"></a>
    <a name="_Toc445747201"></a>
    <a name="_ftnref1"></a>
    <a name="_GoBack"></a>
    <a name="_Toc420004316"></a>
    <a name="_ednref1"></a>
    <a name="_edn1"></a>
    <a name="_Toc88549343"></a>
    <a name="__DdeLink__4707_500493824"></a>
    <a name="__DdeLink__4785_500493824"></a>
    <a name="__DdeLink__4787_500493824"></a>
    <a name="__DdeLink__4791_500493824"></a>
    <a name="_GoBack"></a>
    <a><span lang="EN-US">...</a>
    <a><span lang="EN-US">...</span></a>
